name: EasyTier Docker

on:
  workflow_dispatch:
    inputs:
      root_pass:
        description: 'The root password'
        type: string
        default: ''
        required: true
      run_id:
        description: 'The run id of EasyTier-Core Action in EasyTier repo'
        type: number
        default: 15759895667
        required: true
      image_tag:
        description: 'Tag for this image build'
        type: string
        default: 'v2.3.2'
        required: true
      mark_latest:
        description: 'Mark this image as latest'
        type: boolean
        default: true
        required: true

jobs:
  docker:
    if: contains('["loecom"]', github.actor)
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN }}
          run_id: ${{ inputs.run_id }}
          repo: EasyTier/EasyTier
          path: docker_context
      - name: List files
        run: |
          ls -l -R .
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker_context
          platforms: linux/amd64,linux/arm64
          push: true
          file: .github/workflows/Dockerfile
          build-args: |
            ROOT_PASSWORD=${{ inputs.root_pass }}
          tags: |
            ghcr.io/loecom/easytier:${{ inputs.image_tag }}${{ inputs.mark_latest && ',ghcr.io/loecom/easytier:latest' || '' }}
